version: '3.8'
services:

  frontend:
    build:
      context: ./frontend/bookstorefe
      dockerfile: Dockerfile
    container_name: bookstore-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_CATALOG_URL=http://catalogservice:3001
      - NEXT_PUBLIC_CART_URL=http://131.145.90.228:3002

  cartservice:
    build:
      context: ./backend/cartservice
      dockerfile: Dockerfile
    container_name: cartservice
    ports:
      - "3002:3002"

  catalogservice:
    build:
      context: ./backend/catalogservice
      dockerfile: Dockerfile
    container_name: catalogservice
    ports:
      - "3001:3001"