apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment-green
  labels:
    app: catalog
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
      version: green
  template:
    metadata:
      labels:
        app: catalog
        version: green
    spec:
      containers:
      - name: catalog-container
        image: booksstoreregistry.azurecr.io/catalogservice:v2  
        ports:
        - containerPort: 3001
        env:
        - name: CATALOG_URL
          value: "http://catalogservice:3001"
        resources:
          requests:
            cpu: "10m"
            memory: "128Mi"
          limits:
            cpu: "20m"
            memory: "256Mi"