apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  labels:
    app: cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart-container
        image: booksstoreaksregistry.azurecr.io/cartservice:v1  # Update tag as needed
        ports:
        - containerPort: 3002
        env:
        - name: NEXT_PUBLIC_CART_URL
          value: "http://cartservice:3002"