apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart-container
        image: booksstoreaksregistry.azurecr.io/cartservice:v1  # Update tag as needed
        ports:
        - containerPort: 3002
        env:
        - name: NEXT_PUBLIC_CART_URL
          value: "http://cartservice:3002"
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3