apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog-container
        image: booksstoreaksregistry.azurecr.io/catalogservice:v1  # placeholder tag; will be updated via CI/CD
        ports:
        - containerPort: 3001
        env:
        - name: CATALOG_URL
          value: "http://catalogservice:3001"