apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  labels:
    app: catalog
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
      version: blue
  template:
    metadata:
      labels:
        app: catalog
        version: blue
    spec:
      containers:
      - name: catalog-container
        image: booksstoreregistry.azurecr.io/catalogservice:v1  
        ports:
        - containerPort: 3001
        env:
        - name: CATALOG_URL
          value: "http://catalogservice:3001"
        resources:
          requests:
            cpu: "10m"
            memory: "128Mi"
          limits:
            cpu: "50m"
            memory: "256Mi"
